name: omarchy_emojis
description: An emoji picker for Omarchy
publish_to: 'none' 
version: 0.1.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_omarchy: ^0.1.12
  intl: ^0.20.2
  yaml: ^3.1.3
  path_provider: ^2.1.5
  sqflite: ^2.4.2
  path: ^1.9.1
  sqflite_common_ffi: ^2.3.6
  url_launcher: ^6.3.2
  sprite_image: ^1.0.1
  fuzzywuzzy: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.7.1

flutter:
  assets:
    - assets/
